apiVersion: v1
kind: ConfigMap
metadata:
  name: runtime-env-config
data:
  runtime-env.js: |
    window.__runtime_config__ = {
      MEMBER_URL: 'http://20.249.205.95/api/auth',
      MYSUB_URL: 'http://20.249.205.95/api/mysub',
      RECOMMEND_URL: 'http://20.249.205.95/api/recommend'
    };
